version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres-cards:
    container_name: postgres-cards
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=cards
    volumes:
      - postgres-cards:/var/lib/postgresql/cards
#    ports:
#      - '5433:5432'

  postgres-auth:
    container_name: postgres-auth
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=auth
    volumes:
      - postgres-auth:/var/lib/postgresql/auth
#    ports:
#      - '5433:5432'

  gateway:
    build: ./gateway
    volumes:
      - ./gateway:/usr/src/app
      - gateway-node-modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq

  auth:
    build: ./auth
    env_file:
      - ./auth/.env
    depends_on:
      - rabbitmq
      - postgres-auth
#    volumes:
#      - ./auth:/usr/src/app
#      - auth-node-modules:/usr/src/app/node_modules
#    command: npx prisma migrate deploy #CI/CD


  cards:
    build: ./cards
    volumes:
      - ./cards:/usr/src/app
      - cards-node-modules:/usr/src/app/node_modules
    depends_on:
      - rabbitmq
      - postgres-cards

volumes:
  postgres-auth:
  postgres-cards:
  rabbitmq-data:
  gateway-node-modules:
  cards-node-modules:
#  auth-node-modules:
